# Generated by Django 4.2.3 on 2023-07-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(default="/static/images/post-img1.jpg"),
            preserve_default=False,
        ),
    ]
