# Generated by Django 4.2.3 on 2023-07-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_remove_comment_depth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_order',
        ),
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
