# Generated by Django 4.2.3 on 2023-07-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, choices=[('Life', 'Life'), ('Style', 'Style'), ('Tech', 'Tech'), ('Sport', 'Life'), ('Photo', 'Photo'), ('Develop', 'Develop'), ('Music', 'Music')], max_length=10, null=True),
        ),
    ]
