# Generated by Django 4.2.3 on 2023-07-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_commentfeeling_feeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentfeeling',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postfeeling',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
