# Generated by Django 4.2.3 on 2023-07-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_like_count_post_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='writer',
        ),
    ]
