# Generated by Django 4.2.3 on 2023-07-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_image_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(default='/static/images/profile.jpg'),
        ),
    ]
